menu:
- {name: 'home', url: '/'}
- {name: 'publications', url: '/publications'}
- {name: 'blogs', url: '/blogs'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

blogs:
- {name: 'Curiosity in Reinforcement Learning', url: 'curiosity-in-rl'}

social:
- {icon: 'github', link: 'https://github.com/DriesSmit'}
- {icon: 'twitter', link: 'https://twitter.com/DriesSmit1'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/andries-smit-856901170/'}

contacts:
- {name: 'Dries', email: 'dries.epos@gmail.com', image: 'assets/img/contact.jpg'}
