menu:
- {name: 'home', url: '/'}
- {name: 'publications', url: '/publications'}
- {name: 'blogs', url: '/blogs'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

blogs:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/DriesSmit'}
- {icon: 'twitter', link: 'https://twitter.com/DriesSmit1'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/andries-smit-856901170/'}

contacts:
- {name: 'Dries', email: 'dries.epos@gmail.com', image: 'assets/img/contact.jpg'}
